name: Build ubuntu:base image
on: push
jobs:
 build:
  name: Build Project
  runs-on: ubuntu-20.04
  steps:
  - uses: actions/checkout@v3
  - name: Checkout code and publish from make
    run: make base
  - name: Publish to Docker Hub
    uses: docker/build-push-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
      repository: eat4toast/base
      tags: latest, ${{ github.run_number }}
