name: Build ubuntu:base image
on: push
jobs:
 build-project:
  name: Build Project
  runs-on: ubuntu-20.04
  steps:
  - uses: actions/checkout@v3
  - name: Checkout code and Build image
    run: | 
      make base
      docker tag build-base:dev ${{ secrets.DOCKERHUB_USERNAME }}/build-base:dev
  - name: Login to DockerHub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Publish to Docker Hub
    uses: docker/build-push-action@v3
    with:
        push: true
        tags: eat4toast/build-base:dev
