
name: Build ubuntu:base image
on: push
jobs:
 build-project:
  name: Build Project
  runs-on: ubuntu-20.04
  steps:
  - uses: actions/checkout@v3
  - name: Checkout code and Build image
    run: | 
      git clone --branch=3.1.1 --depth=1 https://github.com/emscripten-core/emsdk.git 
      cd emsdk 
      ./emsdk install 3.1.1
      ./emsdk activate 3.1.1
      mkdir -p /usr/lib/
      cp -r ./upstream/emscripten /usr/lib/
      cd ..
      
      docker pull eat4toast/build-base:dev 		# step1: pull build-base:dev image from docker hub
      docker tag eat4toast/build-base:dev build-base:dev
      
      # step2: here we temporary using Håkon's patch in gr-web building
      git clone --branch=patch-2 --depth=1 https://github.com/haakov/gnuradio-web.git 
      cd haakov_gnuradio
      make webapp
