name: Build ubuntu:base image
on: push
jobs:
 build-project:
  name: Build Project
  runs-on: ubuntu-20.04
  steps:
  - uses: actions/checkout@v3
  - name: Checkout code and Build image
    run: | 
# step0: prepare some dependency package
      echo "{EMSDK_VER}={3.1.1}" >> $GITHUB_ENV
      git clone --branch=${{ env.EMSDK_VER }} --depth=1 https://github.com/emscripten-core/emsdk.git 
      cd emsdk 
      ./emsdk install ${{ env.EMSDK_VER }}
      ./emsdk activate ${{ env.EMSDK_VER }}
      cd ./upstream/ #  source emsdk_env.sh
      mkdir -p /usr/lib/
      cp -r emscripten /usr/lib/
      cd ../..
# step1: pull build-base:dev image from docker hub
      docker pull eat4toast/build-base:dev
      docker tag eat4toast/build-base:dev build-base:dev
      
# step2: here we temporary using Håkon's patch in gr-web building
      git clone --branch=patch-2 --depth=1 https://github.com/haakov/gnuradio-web.git
      cd haakov_gnuradio
      make webapp
